spring.application.name=CART-SERVICE

spring.config.import=configserver:http://localhost:8888

spring.datasource.url = jdbc:postgresql://localhost:5432/employee
spring.datasource.username = postgres
spring.datasource.password = aayushi
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

server.port=9093
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always
resilience4j.circuitbreaker.instances.cartService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.cartService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.cartService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.cartService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.cartService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.cartService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances. sampleService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances. sampleService.sliding-window-type=COUNT_BASED

Management.endpoints.web.exposure.include=*

